config/routes.rb
Todolist::Application.routes.draw do

  root to: "todos#index"
  resources :todos, only: [:index, :create, :destroy]

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def create
    Todo.new(create_params).save
    redirect_to todos_path
  end

  def destroy
    if todo = Todo.find_by(destroy_params)
      todo.destroy
    end
    redirect_to todos_path
  end


  private

  def create_params
    params.require(:todo).permit(:body, :deadline_at)
  end

  def destroy_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_create.html.erb
<%= form_for Todo.new do |f| %>
<table>
  <tr>
    <th><%= Todo.human_attribute_name(:body) %></th>
    <td><%= f.text_field :body %></td>
  </tr>
  <tr>
    <th><%= Todo.human_attribute_name(:deadline_at) %></th>
    <td><%= f.text_field :deadline_at%></td>
  </tr>
</table>
<%= f.submit "作成する", class: "btn btn-primary"%>
<% end %>

app/views/todos/index.html.erb
<h3>TODO list</h3>
<%= render "create" %>
<hr />
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Todo.human_attribute_name(:body) %></th>
      <th><%= Todo.human_attribute_name(:deadline_at) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @todos.each do |todo|%>
    <tr>
       <td><%= todo.body %></td>
       <td><%= todo.deadline_at%></td>
       <td><%= link_to '完了！', todo_path(todo), class: "btn btn-success", method: :delete %></td>
     </tr>
  <% end %>
  </tbody>
</table>
<hr />